### PR TITLE
Update untitled.md

### PR DESCRIPTION
**Pull request by williria**
in interactive mode the dot before the commands are not understood by the program(v0.36), but thanks for this tutorial, it helped a lot, even making me not giving up about this simulator.

### CODE REVIEW

**Comment by mulderp** [comment]
thanks a lot!
what circuit do you want to simulate, what OS are you using, ... ? might we can add some more documentation. have a nice day.

**Comment by williria** [comment]
These days I want to learn how to simulate mixed circuits. The version of
gnucap I am using is the default that comes with linux mint 19.3. I am also
trying to experiment with docker and building gnucap in Ubuntu 20.04. Also
a great day for you too. Many thanks for the help

**Comment by mulderp** [comment]
thanks I had docker image working last year, but I would suggest you try a
build with Cmake
Cmake is a cross platform C++ build tool and is not too difficult to get
started. I added instructions in the CMake section.

https://github.com/mulderp/gnucap_book/blob/master/installing-gnucap.md

Let me know what you think.

For mixed mode simulations maybe we can start discussion in a new github
issue.

Thanks!

**Comment by williria** [comment]
Ok, I will take a look. I really needed to understand better Cmake, since
it is very different of c/c++

**Comment by mulderp** [comment]
CMake is just a build-system generator with a very "basic" like syntax.
The idea is that you just run cmake . to make the necessary configurations
(depedencies for executables and libs).
Then you can run ninja, make, ... to actually build the single steps.

**Comment by williria** [comment]
That is good, but I couldn't run the command. Maybe I needed to install
Ninja?

**Comment by mulderp** [comment]
thanks - yes ninja is necessary 
i will add a download link



> Am 03.08.2020 um 15:44 schrieb Bruno F Sousa <notifications@github.com>:
> 
> ﻿
> That is good, but I couldn't run the command. Maybe I needed to install
> Ninja?
>

**Comment by williria** [comment]
Thanks👍🏽 . One more thing, I could not find the dependency termcap

**Pull request merged**
